PR114-2016-Web1Projekat/Controllers/KomentarController.cs
using PR114_2016_Web1Projekat.Baza;
using PR114_2016_Web1Projekat.Enums;
using PR114_2016_Web1Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class KomentarController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        Dictionary<int, ManifestacijaModel> proslaRezervacija = new Dictionary<int, ManifestacijaModel>();
        // GET: Komentar
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult IndexKomentar(int id)
        {
            ViewBag.id = id;
            return View("DodajKomentar");
        }

        public ActionResult DodajKomentar(KomentarModel formKomentar)
        {
            SesijaStart();
            if (formKomentar.TekstKomentara == null || formKomentar.Ocena==0)
            {
                ViewBag.greska = "Niste uneli sva polja! Pokusajte ponovo!";
                return View("DodavanjeKomentarGreska");
            }
            if (podaciZaSesiju.Komentari.Count > 0)
            {
                foreach (var item in podaciZaSesiju.Komentari.Values)
                {
                    
                    if (item.Kupac.KorisnickoIme == podaciZaSesiju.UlogovaniKorisnik.KorisnickoIme && item.Manifestacija.Id==formKomentar.Manifestacija.Id)
                    {
                        ViewBag.greska = "Vec ste dodali komentar na ovu manifestaciju!";
                        return View("DodavanjeKomentarGreska");
                    }
                }
            }

            KomentarModel komentar = new KomentarModel();
            komentar.Ocena = formKomentar.Ocena;
            komentar.TekstKomentara = formKomentar.TekstKomentara;
            komentar.Id = podaciZaSesiju.Komentari.Count + 1;
            komentar.Manifestacija.Id = formKomentar.Manifestacija.Id;
            komentar.Kupac = podaciZaSesiju.UlogovaniKorisnik;
            podaciZaSesiju.Komentari.Add(komentar.Id, komentar);
            podaciZaSesiju.UpisiKomentarUFajl(komentar);
            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.DaLiJeObrisana == false && item.Manifestacija.DatumiVremeZavrsetka < DateTime.Now && item.StatusKarte == StatusKarte.REZERVISANA)
                {
                    proslaRezervacija.Add(item.Manifestacija.Id, item.Manifestacija);
                    ViewBag.prosle = proslaRezervacija;
                }
            }
            return View("../Kupac/RezProslihMan");
        }

        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }
    }
}

PR114-2016-Web1Projekat/Controllers/KupacController.cs
using PR114_2016_Web1Projekat.Baza;
using PR114_2016_Web1Projekat.Enums;
using PR114_2016_Web1Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class KupacController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        Dictionary<int,KartaModel> karteN=new Dictionary<int, KartaModel>();
        Dictionary<int, KartaModel> karteS = new Dictionary<int, KartaModel>();
        Dictionary<int, KartaModel> karteZ = new Dictionary<int, KartaModel>();
        Dictionary<int, ManifestacijaModel> proslaRezervacija = new Dictionary<int, ManifestacijaModel>();
        Dictionary<int, KomentarModel> odobreniKomentari = new Dictionary<int, KomentarModel>();
        // GET: Kupac
        public ActionResult Index()
        {
            SesijaStart();
            ViewBag.manifestacija = podaciZaSesiju.Manifestacije;
            ViewBag.status = StatusManifestacije.AKTIVNO;
            return View("DostupneManifestacije");
        }
        public ActionResult IndexProfil(int id)
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Manifestacije.Values)
            {
               if(item.Id==id)
                {
                    ViewBag.profil = item;
                }
            }
            return View("ProfilManifestacije");
        }
        public ActionResult IndexSNeRez(int id)
        {
            SesijaStart();
           foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if(item.Manifestacija.Id==id && item.DaLiJeObrisana==false && item.StatusKarte==StatusKarte.NEREZERVISANA)
                {
                     karteS.Add(item.Id, item);
                   
                }
            }
            ViewBag.spisak = karteS;
            return View("SpisakNeRezKarata");
        }
        public ActionResult IndexRezKarte()
        {
            SesijaStart();
            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Kupac.KorisnickoIme==podaciZaSesiju.UlogovaniKorisnik.KorisnickoIme && item.DaLiJeObrisana == false && item.StatusKarte == StatusKarte.REZERVISANA)
                {
                    karteZ.Add(item.Id, item);

                }
            }
          
            

            ViewBag.spisak = karteZ;
           
            return View("RezervisaneKarte");
        }
        public ActionResult IndexZaduzenja()
        {
            SesijaStart();
            ViewBag.zaduzenje = podaciZaSesiju.UlogovaniKorisnik.UkupanDug;
            ViewBag.bodovi = podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova;
            return View("ZaduzenjaIBodovi");
        }
       
        public ActionResult OdobreniKomentari()
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Komentari.Values)
            {
                if(item.DaLiJeIzbrisan==false && item.DaLiJePrihvacen==true)
                {
                    odobreniKomentari.Add(item.Id, item);
                }
            }
            ViewBag.komentari = odobreniKomentari;
            return View("KomentariOdobreni");
        }

        public ActionResult RezervisiKartu(int id)//id karte
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if(item.Id==id)
                {
                    podaciZaSesiju.Karte[item.Id].StatusKarte = StatusKarte.REZERVISANA;
                    podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova += item.Cena / 1000 * 133;
                    podaciZaSesiju.UlogovaniKorisnik.UkupanDug += podaciZaSesiju.Karte[item.Id].Cena;
                    podaciZaSesiju.Karte[item.Id].Kupac = podaciZaSesiju.UlogovaniKorisnik;
                    podaciZaSesiju.IzmeniKarte();
                  
                }
            }

            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Manifestacija.Id ==podaciZaSesiju.Karte[id].Manifestacija.Id && item.DaLiJeObrisana == false && item.StatusKarte == StatusKarte.NEREZERVISANA)
                {
                    karteN.Add(item.Id, item);

                }
            }
            ViewBag.spisak = karteN;
            return View("SpisakNeRezKarata");

        }
        public ActionResult Odustani(int id)//id karte
        {
            SesijaStart();
            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Id == id)
                {
                    if (DateTime.Now <item.Manifestacija.DatumiVremeOdrzavanja.Date.AddDays(7))
                    {
                        podaciZaSesiju.Karte[item.Id].StatusKarte = StatusKarte.NEREZERVISANA;
                        podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova -= item.Cena / 1000 * 133*4;
                        podaciZaSesiju.UlogovaniKorisnik.UkupanDug -= podaciZaSesiju.Karte[item.Id].Cena;
                        podaciZaSesiju.IzmeniKarte();
                        karteZ.Remove(id);
                        karteN.Add(item.Id, item);
                        ViewBag.dobro = "Uspesno ste odustali!";
                        return View("Uspesno");
                        
                    }
                    
                }
            }
            ViewBag.greska = "Ne mozete odustati jos uvek!";
            return View("GreskaOdustajanja");
        }

        public ActionResult KarteKojimaJeManProsla()
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if (item.DaLiJeObrisana == false && item.Manifestacija.DatumiVremeZavrsetka.Date < DateTime.Now.Date && item.StatusKarte == StatusKarte.REZERVISANA)
                {
                   
                        
                        proslaRezervacija.Add(item.Manifestacija.Id, item.Manifestacija);
                        //ViewBag.prosle = proslaRezervacija;
                       
                    
                }
          
            }
            ViewBag.prosle = proslaRezervacija;
            return View("RezProslihMan");
        }

        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }
    }
}

PR114-2016-Web1Projekat/Controllers/LogovanKorisnikController.cs
using PR114_2016_Web1Projekat.Baza;
using PR114_2016_Web1Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class LogovanKorisnikController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        // GET: LogovanKorisnik
        public ActionResult Index()
        {
            SesijaStart();
            ViewBag.registrovan = podaciZaSesiju.UlogovaniKorisnik;
            return View("LogovanKorisnikKupac");
        }
        public ActionResult IndexAdmin()
        {
            SesijaStart();
            ViewBag.registrovan = podaciZaSesiju.UlogovaniKorisnik;
            return View("LogovanKorisnikAdministrator");
        }
        public ActionResult IndexProdavac()
        {
            SesijaStart();
            ViewBag.registrovan = podaciZaSesiju.UlogovaniKorisnik;
            return View("LogovanKorisnikProdavac");
        }

        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }
    }
}

PR114-2016-Web1Projekat/Views/Kupac/DostupneManifestacije.cshtml
@{
    ViewBag.Title = "DostupneManifestacije";
    Layout = null;
}



<head>
    <title>Dostupne manifestacije</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        #div1 {
            background-color: darksalmon;
        }

        #buttonSaznaj {
            background-color: cornflowerblue;
        }
    </style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak dostupnih manifestacija:</h1>
    @foreach (var item in ViewBag.manifestacija.Values)
    {
        if (item.DaLiJeObrisana == false && item.Status == ViewBag.status)
        {
            <div id="div1">
                <p><b>Naziv manifestacije:</b> <i>@item.Naziv </i></p>
                <p><b>Tip manifestacije:</b> <i>@item.TipManifestacije </i></p>
                <p><b>Vreme pocetka odrzavanja:</b> <i> @item.DatumiVremeOdrzavanja </i></p>
                <p><b>Mesto odrzavanja:</b> <i>@item.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj </i></p>
                <input type="button" value="Saznaj vise" id="buttonSaznaj" onclick="location.href='@Url.Action("IndexProfil", "Kupac", new { id = (int)@item.Id })'" />
            </div>
        }
    }
    <a href="@Url.Action("Index","LogovanKorisnik")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Kupac/GreskaOdustajanja.cshtml
@{
    ViewBag.Title = "GreskaOdustajanja";
    Layout = null;
}


<head>
    <title>Greska!</title>
    <style>
        p {
            background-color: red;
            text-align: center;
            color: white;
            font-size: larger;
            margin-top: 20%;
        }

        body {
            background-color: white;
        }
    </style>
</head>
<body>
    <p><b>@ViewBag.greska</b></p>
    <a href="@Url.Action("IndexRezKarte","Kupac")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Kupac/KomentariOdobreni.cshtml
@{
    ViewBag.Title = "KomentariOdobreni";
    Layout = null;
}

<head>
    <title>Komentari</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        #div1 {
            background-color: darksalmon;
        }

        #buttonPrihvacanje {
            background-color: cornflowerblue;
        }
    </style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak komentara:</h1>
    @foreach (var item in ViewBag.komentari.Values)
    {

        if (item.DaLiJeIzbrisan == false)
        {
            <div id="div1">
                <p><b>ID manifestacije:</b> <i>@item.Manifestacija.Id </i></p>
                <p><b>Komentar:</b> <i>@item.TekstKomentara </i></p>
                <p><b>Ocena:</b> <i>@item.Ocena </i></p>
                <p><b>Prihvacen:</b> <i>@item.DaLiJePrihvacen </i></p>

            </div>
        }

    }
    <a href="@Url.Action("Index", "LogovanKorisnik")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Kupac/NemaProslih.cshtml
@{
    ViewBag.Title = "NemaProslih";
    Layout = null;
}

<head>
    <title>Greska!</title>
    <style>
        p {
            background-color: red;
            text-align: center;
            color: white;
            font-size: larger;
            margin-top: 20%;
        }

        body {
            background-color: white;
        }
    </style>
</head>
<body>
    <p><b>@ViewBag.greska</b></p>
    <a href="@Url.Action("IndexRezKarte","Kupac")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Kupac/ProfilManifestacije.cshtml
@{
    ViewBag.Title = "ProfilManifestacije";
    Layout = null;
}
<head>
    <title>Profil korisnika</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        img {
            border-radius: 50%;
            display: block;
            margin-left: auto;
            margin-right: auto;
            width: 300px;
            height: 300px;
        }

        p {
            text-align: center;
        }

        #div1 {
            background-color: cornflowerblue;
            margin-left:auto;
            margin-right:auto;
        }

        input {
            display: block;
            margin-left: auto;
            margin-right: auto;
            background-color: antiquewhite;
            width: 150px;
            height: 30px;
        }
    </style>
</head>
<body>
    <div id="div1">
        <img src="~/Slike/@ViewBag.profil.PosterURL" />
        <p><b>NAZIV: </b> <i>@ViewBag.profil.Naziv</i></p>
        <p><b>TIP: </b> <i>@ViewBag.profil.TipManifestacije</i></p>
        <p><b>BROJ MESTA: </b> <i>@ViewBag.profil.BrojMesta</i></p>
        <p><b>DATUM I VREME ODRZAVANJA </b> <i>@ViewBag.profil.DatumiVremeOdrzavanja</i></p>
        <p><b>DATUM I VREME ZAVRSETKA: </b> <i>@ViewBag.profil.DatumiVremeZavrsetka</i></p>
        <p><b>CENA REGULARNE KARTE: </b> <i>@ViewBag.profil.CenaREGULARKarte</i></p>
        <p><b>STATUS: </b> <i>@ViewBag.profil.Status</i></p>
        <p><b>MESTO ODRZAVANJA: </b> <i>@ViewBag.profil.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj</i></p>
        <input type="button" value="Rezervisi karte" onclick="location.href='@Url.Action("IndexSNeRez","Kupac", new { id = (int)ViewBag.profil.Id })'" />
        <br />
    </div>
</body>

PR114-2016-Web1Projekat/Views/Kupac/RezProslihMan.cshtml
@{
    ViewBag.Title = "RezProslihMan";
    Layout = null;
}

<head>
    <title>Komentar</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        #div1 {
            background-color: darksalmon;
        }

        #buttonKomentar {
            background-color: cornflowerblue;
        }
    </style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak manifestacija na kojima mozete ostaviti komentar:</h1>

    @foreach (var item in ViewBag.prosle.Values)
    {

        <div id="div1">
            <p><b>Naziv:</b> <i>@item.Naziv</i></p>
            <p><b>Tip manifestacije:</b> <i>@item.TipManifestacije</i></p>
            <p><b>Mesto odrzavanja:</b> <i>@item.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj </i></p>
            <input type="button" value="Dodaj komentar" id="buttonKomentar" onclick="location.href='@Url.Action("IndexKomentar", "Komentar", new { id = (int)@item.Id })'" />
        </div>

    }

    <a href="@Url.Action("Index", "LogovanKorisnik")">Vrati se nazad</a>


</body>

PR114-2016-Web1Projekat/Views/Kupac/RezervisaneKarte.cshtml
@{
    ViewBag.Title = "RezervisaneKarte";
    Layout = null;
}


<head>
    <title>Rezervisane karte</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        #div1 {
            background-color: darksalmon;
        }

        #buttonOdustani {
            background-color: cornflowerblue;
        }
    </style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak karata koje su rezervisane:</h1>
    @foreach (var item in ViewBag.spisak.Values)
    {
        <div id="div1">
            <p><b>Tip:</b> <i>@item.TipKarte</i></p>
            <p><b>Cena:</b> <i>@item.Cena </i></p>
            <p><b>Status:</b> <i> @item.StatusKarte </i></p>
            <input type="button" value="Odustani" id="buttonOdustani" onclick="location.href='@Url.Action("Odustani", "Kupac", new { id = (int)@item.Id })'" />
        </div>
    }
    <a href="@Url.Action("Index", "LogovanKorisnik")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Kupac/SpisakNeRezKarata.cshtml
@{
    ViewBag.Title = "SpisakNeRezKarata";
    Layout = null;
}



<head>
    <title>Nerezerisane karte</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        #div1 {
            background-color: darksalmon;
        }

        #buttonRezervisi {
            background-color: cornflowerblue;
        }
    </style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak karata koje jos uvek nisu rezervisane:</h1>
    @foreach (var item in ViewBag.spisak.Values)
    {
       
            <div id="div1">
                <p><b>Tip:</b> <i>@item.TipKarte</i></p>
                <p><b>Cena:</b> <i>@item.Cena </i></p>
                <p><b>Status:</b> <i> @item.StatusKarte </i></p>
                <input type="button" value="Rezervisi" id="buttonRezervisi" onclick="location.href='@Url.Action("RezervisiKartu", "Kupac", new { id = (int)@item.Id })'" />
            </div>
        
    }

</body>

PR114-2016-Web1Projekat/Views/Kupac/Uspesno.cshtml
@{
    ViewBag.Title = "Uspesno";
    Layout = null;
}
<head>
    <title>Greska!</title>
    <style>
        p {
            background-color: green;
            text-align: center;
            color: white;
            font-size: larger;
            margin-top: 20%;
        }

        body {
            background-color: white;
        }
    </style>
</head>
<body>
    <p><b>@ViewBag.dobro</b></p>
</body>

PR114-2016-Web1Projekat/Views/Kupac/ZaduzenjaIBodovi.cshtml
@{
    ViewBag.Title = "ZaduzenjaIBodovi";
    Layout = null;
}

<head>
    <title>Bodovi i zaduzenja</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        p {
            text-align: center;
        }

        #div1 {
            background-color: cornflowerblue;
            margin-left: auto;
            margin-right: auto;
        }

       
    </style>
</head>
<body>
    <div id="div1">
        <p><b>BODOVI: </b> <i>@ViewBag.bodovi</i></p>
        <p><b>ZADUZENJE: </b> <i>@ViewBag.zaduzenje</i> rsd</p>
        <br />
    </div>
    <a href="@Url.Action("Index", "LogovanKorisnik")">Vrati se nazad</a>
</body>