PR114-2016-Web1Projekat/Controllers/EnteringController.cs
using PR114_2016_Web1Projekat.Baza;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class EnteringController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        // GET: Entering
        public ActionResult Index()
        {
           
            SesijaStart();
            return View();
        }

        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }

    }
}

PR114-2016-Web1Projekat/Controllers/ManifestacijeSpisakController.cs
using PR114_2016_Web1Projekat.Baza;
using PR114_2016_Web1Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class ManifestacijeSpisakController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        // GET: ManifestacijeSpisak
        public ActionResult Index()
        {
            SesijaStart();
            ViewBag.sortiranRecnikManifestacija = NajskorijaManifestacija();
            return View("Manifestacije");
        }

        public Dictionary<string, ManifestacijaModel> NajskorijaManifestacija()
        {
            DateTime danasnjiDatum = DateTime.Now;
            
            Dictionary<string, ManifestacijaModel> noviRecnikManifestacija = new Dictionary<string, ManifestacijaModel>();
            foreach(var item in podaciZaSesiju.Manifestacije.Values)
            {
                if(item.DatumiVremeOdrzavanja.Month==danasnjiDatum.Month)
                {
                    if(item.DatumiVremeOdrzavanja.Day>danasnjiDatum.Day)
                    {
                        noviRecnikManifestacija.Add(item.Naziv, item);
                    }
                    else if(item.DatumiVremeOdrzavanja.Day == danasnjiDatum.Day && item.DatumiVremeOdrzavanja.Hour>danasnjiDatum.Hour)
                    {
                        noviRecnikManifestacija.Add(item.Naziv, item);
                    }
                }
                else if(item.DatumiVremeOdrzavanja.Month>danasnjiDatum.Month)
                {
                    noviRecnikManifestacija.Add(item.Naziv, item);
                }
                else if(item.DatumiVremeOdrzavanja.Year>danasnjiDatum.Year)
                {
                    noviRecnikManifestacija.Add(item.Naziv, item);
                }
 
            }
            return noviRecnikManifestacija.OrderBy(x => x.Value.DatumiVremeOdrzavanja).ToDictionary(x => x.Key, x => x.Value);

        }




        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }
    }
}

PR114-2016-Web1Projekat/Views/Entering/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@{
    Layout = null;
}

<head>
    <title>Dobrodosli!</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }
        form {
            background-color:aliceblue;
            height: 300px;
            width: 500px;
            display: inline-block;
        }
        #div1 {
            display: block;
            text-align: center;
        }
        #div2 {
            margin-left:auto;
        }
        input {
            height: 50px;
            width: 400px;
            border-style: solid;
        }
        h1{
            text-align:center;
        }
        #ulogujSeButton{
            text-align:center;
            background-color:deepskyblue;
        }
        p{
            text-align:center;
            background-color:beige;
            font-size:larger;
        }
    </style>
</head>
<body>
    <h1 style="color: aliceblue">Dobrodosli na sajt za rezervaciju ulaznica!</h1>
    <div id="div1">
        <form class="form-element" method="post" action="/Register/LogovanjeKorisnika">
            <br />
            <br />
            <br />
            <input type="text" name="KorisnickoIme" placeholder="Korisnicko ime" id="korisnickoIme" />
            <br />
            <br />
            <br />
            <input type="password" name="Lozinka" id="sifraKorisnika" placeholder="Sifra" />
            <br />
            <br />
            <br />
            <input id="ulogujSeButton" type="submit" value="Uloguj se"/>
        </form>
    </div>
    <div id="div2">
       <p>Jos uvek nemas nalog? <a href="@Url.Action("Index","Register")">Registruj se</a></p> 
       <p>Ovde mozes videti aktuelne manifestacije koje ce se odrzati ---> <a href="@Url.Action("Index","ManifestacijeSpisak")">Pogledaj manifestacije</a></p>
    </div>
</body>