PR114-2016-Web1Projekat/Controllers/AdminController.cs
using PR114_2016_Web1Projekat.Baza;
using PR114_2016_Web1Projekat.Enums;
using PR114_2016_Web1Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class AdminController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        Dictionary<int, ManifestacijaModel> novo = new Dictionary<int, ManifestacijaModel>();
        // GET: Admin
        public ActionResult Index()
        {
            SesijaStart();
            
            return View("DodajKupca");
        }
        public ActionResult Index1()
        {
            SesijaStart();
            ViewBag.Manifestacije = podaciZaSesiju.Manifestacije;
            ViewBag.aktivan = StatusManifestacije.AKTIVNO;
            return View("IzlistajManifestacije");
        }
        public ActionResult IndexKarte()
        {
            SesijaStart();
            ViewBag.karte = podaciZaSesiju.Karte;
            return View("IzlistajKarte");
        }
        public ActionResult IndexKupci()
        {
            SesijaStart();
            ViewBag.kupci = podaciZaSesiju.Kupci;
            return View("IzlistajKorisnike");
        }
        public ActionResult IndexProdavci()
        {
            SesijaStart();
            ViewBag.prodavci = podaciZaSesiju.Prodavci;
            return View("IzlistajProdavce");
        }
        public ActionResult Komentari()
        {
            SesijaStart();
            ViewBag.komentari= podaciZaSesiju.Komentari;
            return View("VidiKomentar");
        }
        [HttpPost]
        public ActionResult DodajProdavca(KorisnikModel formProdavac)
        {
           
            SesijaStart();
            //sva polja moraju biti popunjena, ako ne, prebaci na view greska
            if (formProdavac.KorisnickoIme == null || formProdavac.Ime == null || formProdavac.Prezime == null)
            {
                ViewBag.greska = "Niste uneli sva polja pri registraciji! Pokusajte ponovo!";
                return View("GreskaDodavanje");
            }
            //korisnicko ime pri registraciji mora da se razlikuje od svih u "bazi", ako ne, prebaci na view greska
            foreach (var a in podaciZaSesiju.Kupci.Values)
            {
                if (a.KorisnickoIme == formProdavac.KorisnickoIme)
                {
                    ViewBag.greska = "Korisnik sa ovim korisnickim imenom vec postoji!";
                    return View("GreskaDodavanja");
                }
            }
            foreach (var a in podaciZaSesiju.Administratori.Values)
            {
                if (a.KorisnickoIme == formProdavac.KorisnickoIme)
                {
                    ViewBag.greska = "Korisnik sa ovim korisnickim imenom vec postoji!";
                    return View("GreskaDodavanja");
                }
            }
            foreach (var a in podaciZaSesiju.Prodavci.Values)
            {
                if (a.KorisnickoIme == formProdavac.KorisnickoIme)
                {
                    ViewBag.greska = "Korisnik sa ovim korisnickim imenom vec postoji!";
                    return View("GreskaDodavanja");
                }
            }
            //preuzimanje podataka iz forme
            KorisnikModel prodavac = new KorisnikModel();
            prodavac.KorisnickoIme = formProdavac.KorisnickoIme;
            prodavac.Lozinka = formProdavac.Lozinka;
            prodavac.Ime = formProdavac.Ime;
            prodavac.Prezime = formProdavac.Prezime;
            prodavac.DatumRodjenja = formProdavac.DatumRodjenja;
            prodavac.Pol = formProdavac.Pol;
            prodavac.UlogaKorisnika = Enums.Uloga.PRODAVAC;
            //popunjavanje podataka svih
            podaciZaSesiju.Prodavci.Add(prodavac.KorisnickoIme, prodavac);
            podaciZaSesiju.UpisiProdavcaUFajl(prodavac);
            // podaciZaSesiju.UlogovaniKorisnik = kupac;
            ViewBag.registrovan = podaciZaSesiju.UlogovaniKorisnik;//ovaj korisnik je trenutno ulogovan
            return View("../LogovanKorisnik/LogovanKorisnikAdministrator");
        }
       
        public ActionResult AktivirajManifestaciju(int id)
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Manifestacije.Values)
            {
                if(item.Id==id)
                {
                    if(podaciZaSesiju.Manifestacije[item.Id].Status==StatusManifestacije.NEAKTIVNO)
                    {
                        podaciZaSesiju.Manifestacije[item.Id].Status = StatusManifestacije.AKTIVNO;
                        podaciZaSesiju.IzmeniManifestacije();
                    }
                    else
                    {
                        ViewBag.greska = "Ova manifestacija je vec aktivna!";
                        return View("GreskaAktivacije");
                    }
                }
            }
            ViewBag.manifestacije = podaciZaSesiju.Manifestacije;
            return View("IzlistajManifestacije");

        }
        public ActionResult ObrisiManifestaciju(int id)
        {

            SesijaStart();
            foreach(var item in podaciZaSesiju.Manifestacije.Values)
            {
                if(item.Id==id)
                {
                    if(podaciZaSesiju.Manifestacije[item.Id].DaLiJeObrisana!=true)
                    {
                        podaciZaSesiju.Manifestacije[item.Id].DaLiJeObrisana = true;
                        podaciZaSesiju.IzmeniManifestacije();

                        foreach(var i in podaciZaSesiju.Karte.Values)
                        {
                            if(i.Manifestacija.Id==item.Id)
                            {
                                i.DaLiJeObrisana = true;
                                podaciZaSesiju.IzmeniKarte();
                            }
                        }
                        foreach (var i in podaciZaSesiju.Komentari.Values)
                        {
                            if (i.Manifestacija.Id == item.Id)
                            {
                                i.DaLiJeIzbrisan = true;
                                podaciZaSesiju.IzmeniKomentare();
                            }
                        }
                    }
                }

            }
           
            ViewBag.manifestacije = podaciZaSesiju.Manifestacije;
            return View("IzlistajManifestacije");
        }

        public ActionResult ObrisiProdavca(string korisnickoIme)
        {
            SesijaStart();
            foreach (var item in podaciZaSesiju.Prodavci.Values)
            {
                if (item.KorisnickoIme==korisnickoIme)
                {
                    if (podaciZaSesiju.Prodavci[item.KorisnickoIme].DaLiJeObrisana != true)
                    {
                        podaciZaSesiju.Prodavci[item.KorisnickoIme].DaLiJeObrisana = true;
                        podaciZaSesiju.IzmeniProdavce();

                        foreach (var i in podaciZaSesiju.Manifestacije.Values)
                        {
                            if (i.ProdavacKojiJeKreirao.KorisnickoIme == item.KorisnickoIme)
                            {
                                i.DaLiJeObrisana = true;
                                podaciZaSesiju.IzmeniManifestacije();

                                foreach (var j in podaciZaSesiju.Karte.Values)
                                {
                                    if (j.Manifestacija.Id == i.Id && j.DaLiJeObrisana!=true)
                                    {
                                        j.DaLiJeObrisana = true;
                                        podaciZaSesiju.IzmeniKarte();
                                    }
                                }

                            }
                        }

                    }
                }

            }

            ViewBag.prodavci = podaciZaSesiju.Prodavci;
            return View("IzlistajProdavce");

        }
        public ActionResult ObrisiKupca(string korisnickoIme)
        {

            SesijaStart();
            foreach (var item in podaciZaSesiju.Kupci.Values)
            {
                if (item.KorisnickoIme == korisnickoIme)
                {
                    if (podaciZaSesiju.Kupci[item.KorisnickoIme].DaLiJeObrisana != true)
                    {
                        podaciZaSesiju.Kupci[item.KorisnickoIme].DaLiJeObrisana = true;
                        podaciZaSesiju.IzmeniKupce();

                        foreach(var karta in podaciZaSesiju.Karte.Values)
                        {
                            if(karta.Kupac.KorisnickoIme==item.KorisnickoIme)
                            {
                                podaciZaSesiju.Karte[karta.Id].StatusKarte = StatusKarte.NEREZERVISANA;
                                podaciZaSesiju.IzmeniKarte();
                            }


                        }
                        foreach (var komentar in podaciZaSesiju.Komentari.Values)
                        {
                            if (komentar.Kupac.KorisnickoIme == item.KorisnickoIme)
                            {
                                podaciZaSesiju.Komentari[komentar.Id].DaLiJeIzbrisan=true;
                                podaciZaSesiju.IzmeniKomentare();
                            }


                        }
                    }

                }
            }
            ViewBag.kupci = podaciZaSesiju.Kupci;
            return View("IzlistajKorisnike");

        }
        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }
    }
}

PR114-2016-Web1Projekat/Controllers/EnteringController.cs
using PR114_2016_Web1Projekat.Baza;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class EnteringController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        // GET: Entering
        public ActionResult Index()
        {
           
            SesijaStart();
            return View();
        }

        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }

    }
}

PR114-2016-Web1Projekat/Controllers/KupacController.cs
using PR114_2016_Web1Projekat.Baza;
using PR114_2016_Web1Projekat.Enums;
using PR114_2016_Web1Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class KupacController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        Dictionary<int,KartaModel> karteN=new Dictionary<int, KartaModel>();
        Dictionary<int, KartaModel> karteS = new Dictionary<int, KartaModel>();
        Dictionary<int, KartaModel> karteZ = new Dictionary<int, KartaModel>();
        Dictionary<int, ManifestacijaModel> proslaRezervacija = new Dictionary<int, ManifestacijaModel>();
        Dictionary<int, KomentarModel> odobreniKomentari = new Dictionary<int, KomentarModel>();
        // GET: Kupac
        public ActionResult Index()
        {
            SesijaStart();
            ViewBag.manifestacija = podaciZaSesiju.Manifestacije;
            ViewBag.status = StatusManifestacije.AKTIVNO;
            return View("DostupneManifestacije");
        }
        public ActionResult IndexProfil(int id)
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Manifestacije.Values)
            {
               if(item.Id==id)
                {
                    ViewBag.profil = item;
                }
            }
            return View("ProfilManifestacije");
        }
        public ActionResult IndexSNeRez(int id)
        {
            SesijaStart();
           foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if(item.Manifestacija.Id==id && item.DaLiJeObrisana==false && item.StatusKarte==StatusKarte.NEREZERVISANA)
                {
                     karteS.Add(item.Id, item);
                   
                }
            }
            ViewBag.spisak = karteS;
            return View("SpisakNeRezKarata");
        }
        public ActionResult IndexRezKarte()
        {
            SesijaStart();
            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Kupac.KorisnickoIme==podaciZaSesiju.UlogovaniKorisnik.KorisnickoIme && item.DaLiJeObrisana == false && item.StatusKarte == StatusKarte.REZERVISANA)
                {
                    karteZ.Add(item.Id, item);

                }
            }
          
            

            ViewBag.spisak = karteZ;
           
            return View("RezervisaneKarte");
        }
        public ActionResult IndexZaduzenja()
        {
            SesijaStart();
            ViewBag.zaduzenje = podaciZaSesiju.UlogovaniKorisnik.UkupanDug;
            ViewBag.bodovi = podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova;
            return View("ZaduzenjaIBodovi");
        }
       
        public ActionResult OdobreniKomentari()
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Komentari.Values)
            {
                if(item.DaLiJeIzbrisan==false && item.DaLiJePrihvacen==true)
                {
                    odobreniKomentari.Add(item.Id, item);
                }
            }
            ViewBag.komentari = odobreniKomentari;
            return View("KomentariOdobreni");
        }

        public ActionResult RezervisiKartu(int id)//id karte
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if(item.Id==id)
                {
                    podaciZaSesiju.Karte[item.Id].StatusKarte = StatusKarte.REZERVISANA;
                    podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova += item.Cena / 1000 * 133;
                    podaciZaSesiju.UlogovaniKorisnik.UkupanDug += podaciZaSesiju.Karte[item.Id].Cena;
                    podaciZaSesiju.Karte[item.Id].Kupac = podaciZaSesiju.UlogovaniKorisnik;
                    podaciZaSesiju.IzmeniKarte();
                  
                }
            }

            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Manifestacija.Id ==podaciZaSesiju.Karte[id].Manifestacija.Id && item.DaLiJeObrisana == false && item.StatusKarte == StatusKarte.NEREZERVISANA)
                {
                    karteN.Add(item.Id, item);

                }
            }
            ViewBag.spisak = karteN;
            return View("SpisakNeRezKarata");

        }
        public ActionResult Odustani(int id)//id karte
        {
            SesijaStart();
            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Id == id)
                {
                    if (DateTime.Now <item.Manifestacija.DatumiVremeOdrzavanja.Date.AddDays(7))
                    {
                        podaciZaSesiju.Karte[item.Id].StatusKarte = StatusKarte.NEREZERVISANA;
                        podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova -= item.Cena / 1000 * 133*4;
                        podaciZaSesiju.UlogovaniKorisnik.UkupanDug -= podaciZaSesiju.Karte[item.Id].Cena;
                        podaciZaSesiju.IzmeniKarte();
                        karteZ.Remove(id);
                        karteN.Add(item.Id, item);
                        ViewBag.dobro = "Uspesno ste odustali!";
                        return View("Uspesno");
                        
                    }
                    
                }
            }
            ViewBag.greska = "Ne mozete odustati jos uvek!";
            return View("GreskaOdustajanja");
        }

        public ActionResult KarteKojimaJeManProsla()
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if (item.DaLiJeObrisana == false && item.Manifestacija.DatumiVremeZavrsetka.Date < DateTime.Now.Date && item.StatusKarte == StatusKarte.REZERVISANA)
                {
                   
                        
                        proslaRezervacija.Add(item.Manifestacija.Id, item.Manifestacija);
                        //ViewBag.prosle = proslaRezervacija;
                       
                    
                }
          
            }
            ViewBag.prosle = proslaRezervacija;
            return View("RezProslihMan");
        }

        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }
    }
}

PR114-2016-Web1Projekat/Views/LogovanKorisnik/LogovanKorisnikAdministrator.cshtml
@{
    ViewBag.Title = "LogovanKorisnikAdministrator";
    Layout = null;
}
<head>
    <title>Administrator</title>
    <style>
        h1{
            background-color:aliceblue;
            text-align:center;
        }
        body {
            background-image: url('../../Slike/ticket.jpg');
        }
        p{
            background-color:aliceblue;
            font-size:larger;
            text-align:center;
        }
        input {
            background-color: deepskyblue;
            text-align: center;
            height: 50px;
            width: 500px;
            margin-left:30%;
        }
    </style>
</head>
<body>
    <h1>Administrator: @ViewBag.registrovan.Ime</h1>
    <p>Izaberite opciju:</p>
    <input type="button" value="DODAJ PRODAVCA" onclick="location.href='@Url.Action("Index","Admin")'" />
    <input type="button" value="Profil" onclick="location.href='@Url.Action("Index","Profil")'" />
    <input type="button" value="MANIFESTACIJE" onclick="location.href='@Url.Action("Index1","Admin")'" />
    <input type="button" value="KARTE" onclick="location.href='@Url.Action("IndexKarte","Admin")'" />
    <input type="button" value="KUPCI" onclick="location.href='@Url.Action("IndexKupci","Admin")'" />
    <input type="button" value="PRODAVCI" onclick="location.href='@Url.Action("IndexProdavci","Admin")'" />
    <input type="button" value="KOMENTARI" onclick="location.href='@Url.Action("Komentari","Admin")'" />
    <input type="button" value="Log out" onclick="location.href='@Url.Action("Index","Entering")'" />
</body>

PR114-2016-Web1Projekat/Views/LogovanKorisnik/LogovanKorisnikKupac.cshtml
@{
                /**/

                ViewBag.Title = "LogovanKorisnikKupac";
                Layout = null;
}

<head>
    <title>Kupac</title>
    <style>
        h1 {
            background-color: aliceblue;
            text-align: center;
        }

        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        p {
            background-color: aliceblue;
            font-size: larger;
            text-align: center;
        }

        input {
            background-color: deepskyblue;
            text-align: center;
            height: 50px;
            width: 500px;
            margin-left: 30%;
        }
    </style>
</head>
<body>
    <h1>Kupac: @ViewBag.registrovan.Ime</h1>
    <p>Izaberite opciju:</p>
    <input type="button" value="Profil" onclick="location.href='@Url.Action("Index","Profil")'" />
    <input type="button" value="DOSTUPNE MANIFESTACIJE" onclick="location.href='@Url.Action("Index","Kupac")'" />
    <input type="button" value="REZERVISANE KARTE" onclick="location.href='@Url.Action("IndexRezKarte","Kupac")'" />
    <input type="button" value="ZADUZENJE I BODOVI" onclick="location.href='@Url.Action("IndexZaduzenja","Kupac")'" />
    <input type="button" value="DODAJ KOMENTAR" onclick="location.href='@Url.Action("KarteKojimaJeManProsla","Kupac")'" />
    <input type="button" value="KOMENTARI" onclick="location.href='@Url.Action("OdobreniKomentari","Kupac")'" />
    <input type="button" value="Log out" onclick="location.href='@Url.Action("Index","Entering")'" />
</body>

PR114-2016-Web1Projekat/Views/LogovanKorisnik/LogovanKorisnikProdavac.cshtml
@{
    ViewBag.Title = "LogovanKorisnikProdavac";
    Layout = null;
}
<head>
    <title>Prodavac</title>
    <style>
        h1 {
            background-color: aliceblue;
            text-align: center;
        }

        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        p {
            background-color: aliceblue;
            font-size: larger;
            text-align: center;
        }

        input {
            background-color: deepskyblue;
            text-align: center;
            height: 50px;
            width: 500px;
            margin-left: 30%;
        }
    </style>
</head>
<body>
    <h1>Prodavac: @ViewBag.registrovan.Ime</h1>
    <p>Izaberite opciju:</p>
    <input type="button" value="DODAJ MANIFESTACIJU" onclick="location.href='@Url.Action("Index","Prodavac")'" />
    <input type="button" value="PREGLED SVIH MANIFESTACIJA" onclick="location.href='@Url.Action("SveManifestacijeProdavca","Prodavac")'" />
    <input type="button" value="PRIHVATI KOMENTARE" onclick="location.href='@Url.Action("KomentariZaPrihvacanje","Prodavac")'" />
    <input type="button" value="PREGLED REZERVISANIH KARTI" onclick="location.href='@Url.Action("RezervisaneKarte","Prodavac")'" />
    <input type="button" value="KOMENTARI" onclick="location.href='@Url.Action("SveKom","Prodavac")'" />
    <input type="button" value="Profil" onclick="location.href='@Url.Action("Index","Profil")'" />
    <input type="button" value="Log out" onclick="location.href='@Url.Action("Index","Entering")'" />
</body>