PR114-2016-Web1Projekat/Controllers/KupacController.cs
using PR114_2016_Web1Projekat.Baza;
using PR114_2016_Web1Projekat.Enums;
using PR114_2016_Web1Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class KupacController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        Dictionary<int,KartaModel> karteN=new Dictionary<int, KartaModel>();
        Dictionary<int, KartaModel> karteS = new Dictionary<int, KartaModel>();
        Dictionary<int, KartaModel> karteZ = new Dictionary<int, KartaModel>();
        Dictionary<int, ManifestacijaModel> proslaRezervacija = new Dictionary<int, ManifestacijaModel>();
        Dictionary<int, KomentarModel> odobreniKomentari = new Dictionary<int, KomentarModel>();
        // GET: Kupac
        public ActionResult Index()
        {
            SesijaStart();
            ViewBag.manifestacija = podaciZaSesiju.Manifestacije;
            ViewBag.status = StatusManifestacije.AKTIVNO;
            return View("DostupneManifestacije");
        }
        public ActionResult IndexProfil(int id)
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Manifestacije.Values)
            {
               if(item.Id==id)
                {
                    ViewBag.profil = item;
                }
            }
            return View("ProfilManifestacije");
        }
        public ActionResult IndexSNeRez(int id)
        {
            SesijaStart();
           foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if(item.Manifestacija.Id==id && item.DaLiJeObrisana==false && item.StatusKarte==StatusKarte.NEREZERVISANA)
                {
                     karteS.Add(item.Id, item);
                   
                }
            }
            ViewBag.spisak = karteS;
            return View("SpisakNeRezKarata");
        }
        public ActionResult IndexRezKarte()
        {
            SesijaStart();
            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Kupac.KorisnickoIme==podaciZaSesiju.UlogovaniKorisnik.KorisnickoIme && item.DaLiJeObrisana == false && item.StatusKarte == StatusKarte.REZERVISANA)
                {
                    karteZ.Add(item.Id, item);

                }
            }
          
            

            ViewBag.spisak = karteZ;
           
            return View("RezervisaneKarte");
        }
        public ActionResult IndexZaduzenja()
        {
            SesijaStart();
            ViewBag.zaduzenje = podaciZaSesiju.UlogovaniKorisnik.UkupanDug;
            ViewBag.bodovi = podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova;
            return View("ZaduzenjaIBodovi");
        }
       
        public ActionResult OdobreniKomentari()
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Komentari.Values)
            {
                if(item.DaLiJeIzbrisan==false && item.DaLiJePrihvacen==true)
                {
                    odobreniKomentari.Add(item.Id, item);
                }
            }
            ViewBag.komentari = odobreniKomentari;
            return View("KomentariOdobreni");
        }

        public ActionResult RezervisiKartu(int id)//id karte
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if(item.Id==id)
                {
                    podaciZaSesiju.Karte[item.Id].StatusKarte = StatusKarte.REZERVISANA;
                    podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova += item.Cena / 1000 * 133;
                    podaciZaSesiju.UlogovaniKorisnik.UkupanDug += podaciZaSesiju.Karte[item.Id].Cena;
                    podaciZaSesiju.Karte[item.Id].Kupac = podaciZaSesiju.UlogovaniKorisnik;
                    podaciZaSesiju.IzmeniKarte();
                  
                }
            }

            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Manifestacija.Id ==podaciZaSesiju.Karte[id].Manifestacija.Id && item.DaLiJeObrisana == false && item.StatusKarte == StatusKarte.NEREZERVISANA)
                {
                    karteN.Add(item.Id, item);

                }
            }
            ViewBag.spisak = karteN;
            return View("SpisakNeRezKarata");

        }
        public ActionResult Odustani(int id)//id karte
        {
            SesijaStart();
            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.Id == id)
                {
                    if (DateTime.Now <item.Manifestacija.DatumiVremeOdrzavanja.Date.AddDays(7))
                    {
                        podaciZaSesiju.Karte[item.Id].StatusKarte = StatusKarte.NEREZERVISANA;
                        podaciZaSesiju.UlogovaniKorisnik.BrojSakupljenihBodova -= item.Cena / 1000 * 133*4;
                        podaciZaSesiju.UlogovaniKorisnik.UkupanDug -= podaciZaSesiju.Karte[item.Id].Cena;
                        podaciZaSesiju.IzmeniKarte();
                        karteZ.Remove(id);
                        karteN.Add(item.Id, item);
                        ViewBag.dobro = "Uspesno ste odustali!";
                        return View("Uspesno");
                        
                    }
                    
                }
            }
            ViewBag.greska = "Ne mozete odustati jos uvek!";
            return View("GreskaOdustajanja");
        }

        public ActionResult KarteKojimaJeManProsla()
        {
            SesijaStart();
            foreach(var item in podaciZaSesiju.Karte.Values)
            {
                if (item.DaLiJeObrisana == false && item.Manifestacija.DatumiVremeZavrsetka.Date < DateTime.Now.Date && item.StatusKarte == StatusKarte.REZERVISANA)
                {
                   
                        
                        proslaRezervacija.Add(item.Manifestacija.Id, item.Manifestacija);
                        //ViewBag.prosle = proslaRezervacija;
                       
                    
                }
          
            }
            ViewBag.prosle = proslaRezervacija;
            return View("RezProslihMan");
        }

        private void SesijaStart()
        {
            podaciZaSesiju = (OperacijePodataka)Session["PodaciZaSesiju"];
            if (podaciZaSesiju == null)
            {
                podaciZaSesiju = new OperacijePodataka();
                Session["PodaciZaSesiju"] = podaciZaSesiju;
            }

            podaciZaSesiju.UcitajPodatkeIznova();

        }
    }
}

PR114-2016-Web1Projekat/Controllers/ProdavacController.cs
using PR114_2016_Web1Projekat.Baza;
using PR114_2016_Web1Projekat.Enums;
using PR114_2016_Web1Projekat.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PR114_2016_Web1Projekat.Controllers
{
    public class ProdavacController : Controller
    {
        OperacijePodataka podaciZaSesiju;
        Dictionary<int, ManifestacijaModel> mani = new Dictionary<int, ManifestacijaModel>();
        Dictionary<int, ManifestacijaModel> maniOdobri = new Dictionary<int, ManifestacijaModel>();
        Dictionary<int, ManifestacijaModel> maniOdbij = new Dictionary<int, ManifestacijaModel>();
        Dictionary<int, KartaModel> rezKarte = new Dictionary<int, KartaModel>();
        Dictionary<int, KomentarModel> komentari = new Dictionary<int, KomentarModel>();
        public int param;
       
        // GET: Prodavac
        public ActionResult Index()
        {
            SesijaStart();
            return View("DodajManifestaciju");
        }
        public ActionResult Index1(int id)
        {
            SesijaStart();
            param = id;
            ViewBag.id = param;
            ViewBag.manifestacijaModel = podaciZaSesiju.Manifestacije[id];
           
            return View("IzmeniManifestaciju");
        }
        public ActionResult KomentariZaPrihvacanje()
        {
            SesijaStart();

            
            foreach(var item in podaciZaSesiju.Manifestacije.Values)
            {
                if(item.ProdavacKojiJeKreirao.KorisnickoIme==podaciZaSesiju.UlogovaniKorisnik.KorisnickoIme && item.DaLiJeObrisana==false)
                {
                    mani.Add(item.Id, item);
                   
                }
            }
            ViewBag.komentari = podaciZaSesiju.Komentari;
            ViewBag.ulogovan = podaciZaSesiju.UlogovaniKorisnik;
            ViewBag.manifestacije = mani;
            return View("KomentariZaPrihvacanje");
        }
        public ActionResult RezervisaneKarte()
        {
            SesijaStart();

            foreach (var item in podaciZaSesiju.Karte.Values)
            {
                if (item.DaLiJeObrisana == false && item.StatusKarte == StatusKarte.REZERVISANA)
                {
                    foreach (var jtem in podaciZaSesiju.Manifestacije.Values)
                    {

                        if (item.Manifestacija.Id == jtem.Id)
                        {
                            
                                
                                if (jtem.ProdavacKojiJeKreirao.KorisnickoIme == podaciZaSesiju.UlogovaniKorisnik.KorisnickoIme)
                                {
                                    rezKarte.Add(item.Id, item);
                                }
                            
                        }

                    }
                }
            }
           
            ViewBag.spisak = rezKarte;
            return View("RezKarte");
        }
        public ActionResult SveKom()
        {
            SesijaStart();
            foreach(var  item in podaciZaSesiju.Komentari.Values)
            {
                if(item.DaLiJeIzbrisan==false)
                {
                    komentari.Add(item.Id, item);
                }
            }
            ViewBag.komentari = komentari;
            return View("SveKom");
        }
        [HttpPost]
        public ActionResult DodajManifestaciju(ManifestacijaModel formManifestacija)
        {
            SesijaStart();

            if (formManifestacija.Naziv == null || formManifestacija.BrojMesta==0 || formManifestacija.DatumiVremeOdrzavanja==null 
                || formManifestacija.DatumiVremeZavrsetka==null || formManifestacija.CenaREGULARKarte==0 || formManifestacija.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj==null)
            {
                ViewBag.greska = "Niste uneli sve podatke o manifestaciji. Pokusajte ponovo!";
                return View("GreskaDodavanjaManifestacije");
            }
            foreach (var item in podaciZaSesiju.Manifestacije.Values)
            {
                if (item.DatumiVremeOdrzavanja.ToString("hh:mm tt") == formManifestacija.DatumiVremeOdrzavanja.ToString("hh:mm tt") 
                    && item.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj==formManifestacija.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj
                    && item.DaLiJeObrisana==false
                    && item.DatumiVremeOdrzavanja.Date==formManifestacija.DatumiVremeOdrzavanja.Date)
                {
                    ViewBag.greska = "Neka od manifestacija se vec odrzava na ovom mestu u ovo vreme. Pokusajte da zakazete neki drugi termin!";
                    return View("GreskaDodavanjaManifestacije");
                }
            }
            ManifestacijaModel manifestacija = new ManifestacijaModel();
            manifestacija.Id = podaciZaSesiju.Manifestacije.Count + 1;//svaki nov dodat ima za jedan veci id
            manifestacija.Naziv = formManifestacija.Naziv;
            manifestacija.TipManifestacije = formManifestacija.TipManifestacije;
            manifestacija.BrojMesta = formManifestacija.BrojMesta;
            manifestacija.DatumiVremeOdrzavanja = formManifestacija.DatumiVremeOdrzavanja;
            manifestacija.DatumiVremeZavrsetka = formManifestacija.DatumiVremeZavrsetka;
            manifestacija.CenaREGULARKarte = formManifestacija.CenaREGULARKarte;
            manifestacija.Status = StatusManifestacije.NEAKTIVNO;
            manifestacija.MestoOdrzavanja = formManifestacija.MestoOdrzavanja;
            manifestacija.PosterURL = formManifestacija.PosterURL;
            manifestacija.ProdavacKojiJeKreirao.KorisnickoIme = podaciZaSesiju.UlogovaniKorisnik.KorisnickoIme;
            manifestacija.DaLiJeObrisana = false;
            for(int i=0; i<manifestacija.BrojMesta;i++)
            {
                KartaModel karta = new KartaModel();
                karta.StatusKarte = StatusKarte.NEREZERVISANA;
                karta.Id = podaciZaSesiju.Karte.Count + 1;
                karta.Manifestacija = manifestacija;
                karta.DaLiJeObrisana = false;

                if(i%3==0)
                {
                    karta.TipKarte = TipKarte.REGULAR;
                    karta.Cena = manifestacija.CenaREGULARKarte;
                }
                else if(i%3==1)
                {
                    karta.TipKarte = TipKarte.VIP;
                    karta.Cena = manifestacija.CenaREGULARKarte*4;

                }
                else if(i%3==2)
                {
                    karta.TipKarte = TipKarte.FANPIT;
                    karta.Cena = manifestacija.CenaREGULARKarte * 2;
                }
                podaciZaSesiju.Karte.Add(karta.Id, karta);
                podaciZaSesiju.UpisiKarteUFajl(karta);
            }

            //popunjavanje podataka svih
            podaciZaSesiju.Manifestacije.Add(manifestacija.Id, manifestacija);
            podaciZaSesiju.UpisiManifestacijeUFajl(manifestacija);
            ViewBag.registrovan = podaciZaSesiju.UlogovaniKorisnik;//ovaj korisnik je trenutno ulogovan
            return View("../LogovanKorisnik/LogovanKorisnikProdavac");

        }
        public ActionResult SveManifestacijeProdavca()
        {
            SesijaStart();
            Dictionary<int, ManifestacijaModel> manifestacijeKupaca = new Dictionary<int, ManifestacijaModel>();
            foreach(var item in podaciZaSesiju.Manifestacije.Values)
            {
                
                if(item.ProdavacKojiJeKreirao.KorisnickoIme==podaciZaSesiju.UlogovaniKorisnik.KorisnickoIme)
                {
                    manifestacijeKupaca.Add(item.Id, item);
                }

            }

            ViewBag.mojeManifestacije = manifestacijeKupaca;
            return View("ManifestacijeProdavca");


        }
        [HttpPost]
        public ActionResult IzmeniManifestaciju(ManifestacijaModel formIzmenaManifestacija)
        {
            SesijaStart();

            if (formIzmenaManifestacija.Naziv == null  || formIzmenaManifestacija.DatumiVremeOdrzavanja == null
                || formIzmenaManifestacija.DatumiVremeZavrsetka == null || formIzmenaManifestacija.CenaREGULARKarte == 0 || formIzmenaManifestacija.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj == null)
            {
                ViewBag.greska = "Niste uneli sve podatke o manifestaciji. Pokusajte ponovo!";
                return View("GreskaIzmeneManifestacije");
            }
            foreach (var item in podaciZaSesiju.Manifestacije.Values)
            {
                if (item.DatumiVremeOdrzavanja.ToString("hh:mm tt") == formIzmenaManifestacija.DatumiVremeOdrzavanja.ToString("hh:mm tt")
                    && item.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj == formIzmenaManifestacija.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj
                    && item.DaLiJeObrisana==false
                    && item.DatumiVremeOdrzavanja.Date == formIzmenaManifestacija.DatumiVremeOdrzavanja.Date)
                {
                    if (item.Id != formIzmenaManifestacija.Id)
                    {
                        ViewBag.greska = "Neka od manifestacija se vec odrzava na ovom mestu u ovo vreme. Pokusajte da zakazete neki drugi termin!";
                        return View("GreskaIzmeneManifestacije");
                    }
                }
            }
            ManifestacijaModel novaManifestacija = new ManifestacijaModel();
            novaManifestacija.Id = formIzmenaManifestacija.Id;
            novaManifestacija.Naziv = formIzmenaManifestacija.Naziv;
            novaManifestacija.TipManifestacije = formIzmenaManifestacija.TipManifestacije;
            novaManifestacija.BrojMesta = podaciZaSesiju.Manifestacije[formIzmenaManifestacija.Id].BrojMesta;
            novaManifestacija.DatumiVremeOdrzavanja = formIzmenaManifestacija.DatumiVremeOdrzavanja;
            novaManifestacija.DatumiVremeZavrsetka = formIzmenaManifestacija.DatumiVremeZavrsetka;

PR114-2016-Web1Projekat/Views/Prodavac/DodajManifestaciju.cshtml
@{
    ViewBag.Title = "DodajManifestaciju";
    Layout = null;
}

<head>
    <title>Dodaj manifestaciju</title>
    <style>
         body {
            background-image: url('../../Slike/ticket.jpg');
         }
         form {
            background-color: aliceblue;
            height: 1100px;
            width: 700px;
            display: inline-block;
         }
        input {
            height: 50px;
            width: 400px;
            border-style: solid;
        }
        #radio1 {
            width: auto;
            height: auto;
        }

        #radio2 {
            width: auto;
            height: auto;
        }
        #radio3 {
            width: auto;
            height: auto;
        }
        #radio4 {
            width: auto;
            height: auto;
        }
        #div1 {
            display: block;
            text-align: center;
        }
        h1 {
            text-align: center;
            background-color: aliceblue;
        }
    </style>
</head>
<body>
    <h1>Unesi podatke manifestacije:</h1>
    <div id="div1">
        <form class="form-element" method="post" action="/Prodavac/DodajManifestaciju">
            <br />
            <br />
            <br />
            <input type="text" name="Naziv" placeholder="Naziv manifestacije" id="nazivManifestacije" />
            <br />
            <br />
            <p>Tip manifestacije:</p>
            <input id="radio1" type="radio" name="TipManifestacije" value="KONCERT" checked="checked" /> KONCERT &nbsp;
            <input id="radio2" type="radio" name="TipManifestacije" value="FESTIVAL" /> FESTIVAL &nbsp;
            <input id="radio3" type="radio" name="TipManifestacije" value="POZORISTE" /> POZORISTE &nbsp;
            <input id="radio4" type="radio" name="TipManifestacije" value="BIOSKOP" /> BIOSKOP &nbsp;
            <br />
            <br />
            <br />
            <input type="number" name="BrojMesta" id="brojMesta" placeholder="Broj mesta" min="3" max="9" />
            <br />
            <br />
            <br />
            <p>Datum i vreme odrzavanja:</p>
            <input type="datetime-local" name="DatumiVremeOdrzavanja" id="datumIVremeOdrzavanja" />
            <br />
            <br />
            <br />
            <p>Datum i vreme zavrsetka:</p>
            <input type="datetime-local" name="DatumiVremeZavrsetka" id="datumIVremeZavrsetka" />
            <br />
            <br />
            <br />
            <input type="number" name="CenaREGULARKarte" id="cenaRegularKarte" placeholder="Cena regularne karte u RSD" />
            <br />
            <br />
            <br />
            <input type="text" name="MestoOdrzavanja.UlicaiBrojGradPostanskiBroj" id="mestoOdrzavanja" placeholder="Ulica i broj/Grad/Postanski broj" />
            <br />
            <br />
            <br />
            <p>Poster manifestacije:</p>
            <input type="file" name="PosterURL" id="posterURL" multiple="multiple" />
            <br />
            <br />
            <br />
            <input id="dodajManifestacijuButton" type="submit" value="Dodaj" />
        </form>
    </div>
    <a href="@Url.Action("IndexProdavac", "LogovanKorisnik")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Prodavac/GreskaDodavanjaManifestacije.cshtml
@{
    ViewBag.Title = "GreskaDodavanjaManifestacije";
    Layout = null;
}

<head>
    <title>Greska!</title>
    <style>
        p {
            background-color: red;
            text-align: center;
            color: white;
            font-size: larger;
            margin-top: 20%;
        }

        body {
            background-color: white;
        }
    </style>
</head>
<body>
    <p><b>@ViewBag.greska</b></p>
    <a href="@Url.Action("Index","Prodavac")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Prodavac/GreskaIzmeneManifestacije.cshtml
@{
    ViewBag.Title = "GreskaIzmeneManifestacije";
    Layout = null;
}

<head>
    <title>Greska!</title>
    <style>
        p {
            background-color: red;
            text-align: center;
            color: white;
            font-size: larger;
            margin-top: 20%;
        }

        body {
            background-color: white;
        }
    </style>
</head>
<body>
    <p><b>@ViewBag.greska</b></p>
    <a href="@Url.Action("Index","Prodavac")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Prodavac/GreskaPrihvacanja.cshtml
@{
    ViewBag.Title = "GreskaPrihvacanja";
    Layout = null;
}

<head>
    <title>Greska!</title>
    <style>
        p {
            background-color: red;
            text-align: center;
            color: white;
            font-size: larger;
            margin-top: 20%;
        }

        body {
            background-color: white;
        }
    </style>
</head>
<body>
    <p><b>@ViewBag.greska</b></p>
    <a href="@Url.Action("Index","Prodavac")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Prodavac/KomentariZaPrihvacanje.cshtml
@{
    ViewBag.Title = "KomentariZaPrihvacanje";
    Layout = null;
}

<head>
    <title>Komentari</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        #div1 {
            background-color: darksalmon;
        }

        #buttonPrihvacanje {
            background-color: cornflowerblue;
        }
    </style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak komentara za prihvacanje:</h1>
    @foreach (var item in ViewBag.komentari.Values)
    {
        foreach(var i in ViewBag.manifestacije.Values)
        {
            if (item.DaLiJeIzbrisan == false && item.Manifestacija.Id == i.Id)
            {
    <div id="div1">
        <p><b>Naziv manifestacije:</b> <i>@item.Manifestacija.Id </i></p>
        <p><b>Komentar:</b> <i>@item.TekstKomentara </i></p>
        <p><b>Ocena:</b> <i>@item.Ocena </i></p>
        <p><b>Prihvacen:</b> <i>@item.DaLiJePrihvacen </i></p>
        <input id="buttonPrihvacanje" type="button" value="Odobri" onclick="location.href='@Url.Action("OdobriKomentar", "Prodavac", new { id = (int)@item.Id })'" />
        <input id="buttonPrihvacanje" type="button" value="Odbij" onclick="location.href='@Url.Action("OdbijKomentar", "Prodavac", new { id = (int)@item.Id })'" />
    </div>
            }
        }
    }

</body>

PR114-2016-Web1Projekat/Views/Prodavac/ManifestacijeProdavca.cshtml
@{
    ViewBag.Title = "ManifestacijeProdavca";
    Layout = null;
}

<head>
    <title>Dostupne manifestacije</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        #div1 {
            background-color: darksalmon;
        }

        #buttonIzmeni {
            background-color: cornflowerblue;
        }
    </style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak dostupnih manifestacija:</h1>
    @foreach (var item in ViewBag.mojeManifestacije.Values)
    {
        if (item.DaLiJeObrisana == false)
        {
            <div id="div1">
                <p><b>Naziv manifestacije:</b> <i>@item.Naziv </i></p>
                <p><b>Tip manifestacije:</b> <i>@item.TipManifestacije </i></p>
                <p><b>Vreme pocetka odrzavanja:</b> <i> @item.DatumiVremeOdrzavanja </i></p>
                <p><b>Mesto odrzavanja:</b> <i>@item.MestoOdrzavanja.UlicaiBrojGradPostanskiBroj </i></p>
                <p><b>Aktivnost:</b> <i>@item.Status </i></p>
                <input id="buttonIzmeni" type="button" value="Izmeni" onclick="location.href='@Url.Action("Index1", "Prodavac", new { id = (int)@item.Id })'" />
            </div>
        }
    }
    <a href="@Url.Action("IndexProdavac", "LogovanKorisnik")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Prodavac/RezKarte.cshtml
@{
                /**/

                ViewBag.Title = "RezKarte";
                Layout = null;
}
<head>
<title>Rezervisane karte</title>
<style>
    body {
        background-image: url('../../Slike/ticket.jpg');
    }

    #div1 {
        background-color: darksalmon;
    }

    #buttonOdustani {
        background-color: cornflowerblue;
    }
</style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak karata koje su rezervisane:</h1>
    @foreach (var item in ViewBag.spisak.Values)
    {
        <div id="div1">
            <p><b>Rezervisao:</b> <i>@item.Kupac.KorisnickoIme</i></p>
            <p><b>Tip:</b> <i>@item.TipKarte</i></p>
            <p><b>Cena:</b> <i>@item.Cena </i></p>
            <p><b>Status:</b> <i> @item.StatusKarte </i></p>
            <input type="button" value="Odustani" id="buttonOdustani" onclick="location.href='@Url.Action("Odustani", "Kupac", new { id = (int)@item.Id })'" />
        </div>
    }
    <a href="@Url.Action("IndexProdavac", "LogovanKorisnik")">Vrati se nazad</a>
</body>

PR114-2016-Web1Projekat/Views/Prodavac/SveKom.cshtml
@{
    ViewBag.Title = "SveKom";
    Layout = null;
}

<head>
    <title>Komentari</title>
    <style>
        body {
            background-image: url('../../Slike/ticket.jpg');
        }

        #div1 {
            background-color: darksalmon;
        }

        #buttonPrihvacanje {
            background-color: cornflowerblue;
        }
    </style>
</head>
<body>
    <h1 style="background-color:aliceblue">Spisak komentara:</h1>
    @foreach (var item in ViewBag.komentari.Values)
    {

        if (item.DaLiJeIzbrisan == false)
        {
            <div id="div1">
                <p><b>ID manifestacije:</b> <i>@item.Manifestacija.Id </i></p>
                <p><b>Komentar:</b> <i>@item.TekstKomentara </i></p>
                <p><b>Ocena:</b> <i>@item.Ocena </i></p>
                <p><b>Prihvacen:</b> <i>@item.DaLiJePrihvacen </i></p>

            </div>
        }

    }
    <a href="@Url.Action("IndexProdavac", "LogovanKorisnik")">Vrati se nazad</a>
</body>